services:
  license-authority:
    #image: license-authority:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: license-authority
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:////app/data/authority.db
    volumes:
      - ./app:/app/app
      - ./keys/private.pem:/app/keys/private.pem:ro
      - ./keys/public.pem:/app/keys/public.pem:ro
      - ./authority_db_data:/app/data
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  authority_db_data:
